name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master # Якщо основна гілка називається 'main', змініть тут

# Обов'язкові права для нативного деплою через GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Забороняє паралельний деплой, щоб уникнути конфліктів
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Робота 1: Збірка проєкту
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --configuration=production

      # Створюємо файл CNAME для вашого кастомного домену
      - name: Create CNAME file
        run: echo "mini-home.itkamianets.com" > dist/mini-home-hote/browser/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Шлях до папки з готовим білдом
          path: 'dist/mini-home-hote/browser'

  # Робота 2: Розгортання
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Чекаємо, поки завершиться build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4